/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: shakiller (https://sketchfab.com/shakiller)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/island-09dc6dc86afb49e58ecc876f3834d090
Title: Island
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials } = useGLTF('/island (1).glb')
  return (
    <group {...props} dispose={null}>
      <group position={[510.754, 6.742, 238.312]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object035_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[521.341, 6.742, 235.657]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object036_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[531.373, 5.713, 233.024]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object037_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[541.961, 6.742, 230.369]} rotation={[-Math.PI / 2, 0, -1.833]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object038_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[552.094, 5.487, 228.472]} rotation={[-Math.PI / 2, 0, -1.309]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object039_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[562.681, 6.742, 225.817]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object040_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[574.21, 5.166, 220.7]} rotation={[-Math.PI / 2, 0, -2.443]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object041_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[583.455, 5.166, 208.764]} rotation={[-Math.PI / 2, 0, -1.745]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object042_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[446.836, 6.742, 250.692]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object043_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[459.888, 6.742, 249.329]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object044_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[472.261, 5.713, 248.97]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object045_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[482.849, 6.742, 246.314]} rotation={[-Math.PI / 2, 0, -1.833]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object046_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[415.906, 6.742, 245.688]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object047_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[435.495, 6.742, 250.829]} rotation={[-Math.PI / 2, 0, -1.833]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object048_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[425.573, 5.713, 247.806]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object049_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[440.892, 6.913, 231.962]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object050_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[404.393, 5.713, 241.17]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object051_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[392.402, 5.713, 198.196]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object052_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[399.718, 6.638, 156.055]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object053_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[417.836, 5.713, 136.746]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object054_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[413.17, 6.667, 148.286]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object055_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[442.858, 6.742, 142.883]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object056_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[459.017, 6.742, 106.61]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object057_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[435.942, 5.713, 93.92]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object058_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[447.86, 5.713, 208.245]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object059_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[486.036, 17.745, 104.583]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object060_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[500.497, 18.568, 138.11]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object061_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[493.195, 18.568, 124.589]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object062_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[496, 18.568, 115.925]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object063_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[482.229, 17.745, 112.596]} rotation={[-Math.PI / 2, 0, 2.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object064_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[436.621, 5.526, 150.278]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object065_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <group position={[428.273, 6.742, 154.309]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object066_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[0, 0, -6.742]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box017_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[451.108, 0.552, 84.599]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box018_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[448.073, 1.248, 121.55]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box019_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[498.291, 13.242, 90.025]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box020_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[522.454, 13.587, 138.468]}
        rotation={[-Math.PI / 2, 0, 1.745]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box021_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[389.009, 0, 174.207]}
        rotation={[-Math.PI / 2, 0, -0.611]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box022_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[470.525, 0, 215.374]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box023_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[419.631, 0, 211.277]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box024_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[455.201, 0.015, 70.059]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box025_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[538.672, 0.864, 170.126]}
        rotation={[-Math.PI / 2, 0, 1.396]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box026_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[532.123, 0, 210.763]}
        rotation={[-Math.PI / 2, 0, 0.175]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box027_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[587.84, 0.125, 183.201]}
        rotation={[-Math.PI / 2, 0, 0.698]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Box028_Material_#3_0'].geometry}
        material={materials.Material_3}
        position={[557.779, 1.15, 156.317]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle020_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[655.112, 0, 84.257]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle021_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[657.895, 0, 71.738]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle022_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[640.43, 0, 55.12]}
        rotation={[-Math.PI / 2, 0, 1.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle023_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[627.447, 7.047, 61.762]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle024_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[640.993, 3.138, 66.826]}
        rotation={[-Math.PI / 2, 0, 2.793]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle025_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[599.298, 0, 85.947]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle026_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[581.37, 0, 103.218]}
        rotation={[-Math.PI / 2, 0, -2.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle027_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[589.387, 0, 96.616]}
        rotation={[-Math.PI / 2, 0, 0.698]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle028_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[593.12, 0, 94.354]}
        rotation={[-Math.PI / 2, 0, -3.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle029_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[608.648, 7.45, 75.584]}
        rotation={[-Math.PI / 2, 0, 0.302]}
        scale={[1.013, 0.663, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle030_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[607.86, -7.047, 47.317]}
        rotation={[-Math.PI / 2, 0, 1.833]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle031_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[595.047, -7.047, 47.869]}
        rotation={[-Math.PI / 2, 0, 1.833]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle032_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[584.336, -7.047, 51.668]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle033_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[620.797, -7.064, 72.935]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle034_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[613.406, -7.064, 82.794]}
        rotation={[-Math.PI / 2, 0, 0.698]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle035_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[615.27, -2.354, 79.268]}
        rotation={[-Math.PI / 2, 0, -3.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle036_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[620.888, -3.578, 65.463]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle037_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[519.679, -1.434, 48.024]}
        rotation={[-Math.PI / 2, 0, -2.578]}
        scale={[1.013, 0.663, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Circle038_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[524.974, 0, 65.197]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere147_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[528.767, 3.129, 173.315]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere148_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[523.135, 3.129, 174.667]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere149_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[570.825, 14.944, 114.304]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere150_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[575.131, 11.941, 124.518]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere151_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[567.893, 14.944, 123.557]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere152_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[568.945, 14.926, 118.583]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere153_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[578.382, 9.031, 127.063]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere154_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[581.109, 5.095, 129.869]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere155_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[577.165, 2.96, 133.489]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere156_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[574.842, 6.238, 130.59]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere157_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[567.759, 7.157, 133.48]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere158_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[568.455, 11.511, 129.251]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere159_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[546.795, 13.856, 141.302]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere160_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[548.57, 13.288, 130.597]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere161_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[555.099, 13.856, 134.702]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere162_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[550.338, 14.302, 136.528]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere163_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[541.055, 14.302, 127.627]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere164_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[551.265, 14.302, 123.846]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere165_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[560.269, 14.302, 120.42]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere166_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[555.894, 15.373, 122.203]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere167_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[545.93, 15.373, 125.255]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere168_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[561.194, 14.345, 127.632]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere169_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[509.688, 3.129, 185.848]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere170_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[462.048, 3.129, 178.291]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere171_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[467.941, 5.276, 165.55]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere172_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[562.221, 31.391, 104.333]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere173_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[557.423, 29.037, 105.397]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere174_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[553.709, 30.263, 109.302]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere175_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[548.296, 29.418, 109.787]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere176_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[543.772, 30.061, 112.87]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere177_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[538.659, 29.258, 112.846]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere178_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[569.259, 30.753, 78.572]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere179_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[564.462, 29.037, 79.635]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere180_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[559.259, 30.263, 79.139]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere181_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[553.846, 29.418, 79.625]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere182_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[549.146, 31.01, 80.948]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere183_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[544.033, 29.258, 80.924]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere184_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[580.935, 30.263, 78.688]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere185_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[575.522, 29.418, 79.173]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere186_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[584.025, 31.416, 83.986]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere187_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[578.612, 28.464, 84.472]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere188_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[591.345, 27.205, 78.304]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere189_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[585.932, 30.045, 78.789]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere190_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[581.456, 30.263, 89.49]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere191_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[576.043, 28.458, 89.975]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere192_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[588.921, 28.772, 82.318]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere193_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[586.773, 28.464, 88.069]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere194_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[579.695, 28.464, 94.925]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere195_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[593.245, 13.388, 114.07]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere196_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[596.496, 11.092, 116.615]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere197_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[599.223, 7.156, 119.421]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere198_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[595.279, 6.164, 123.042]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere199_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[592.956, 8.298, 120.142]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere200_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[585.873, 9.218, 123.032]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere201_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[586.569, 12.101, 118.803]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere202_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[609.885, 10.342, 109.37]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere203_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[613.136, 9.086, 111.915]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere204_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[615.863, 8.206, 114.721]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere205_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[611.919, 6.36, 118.341]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere206_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[609.596, 8.298, 115.442]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere207_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[604.431, 5.873, 118.332]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere208_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[603.209, 11.329, 114.103]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere209_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[568.053, 2.827, 149.308]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere210_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[562.48, 2.479, 147.429]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere211_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[431.405, 3.235, 164.115]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere212_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[443.912, 4.516, 159.835]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere213_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[456.688, 7.48, 150.5]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere214_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[465.483, 10.644, 143.793]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere215_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[502.964, 14.519, 75.784]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere216_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[511.758, 14.617, 69.077]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere217_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[471.634, 3.129, 176.857]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere218_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[481.968, 3.129, 180.819]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere219_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[494.63, 3.621, 180.08]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere220_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[480.584, 5.276, 171.202]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere221_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[492.834, 5.276, 173.232]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere222_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[486.722, 8.236, 167.493]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere223_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[476.498, 7.438, 165.38]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere224_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[474.386, 5.303, 172.086]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere225_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[486.253, 4.222, 175.579]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere226_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[504.396, 12.913, 160.97]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere227_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[497.103, 12.826, 158.248]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere228_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[492.531, 12.913, 151.632]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere229_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[505.888, 16.229, 115.046]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere230_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[508.336, 15.038, 125.911]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere231_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[524.639, 3.129, 180.243]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere232_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[516.077, 3.129, 179.162]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere233_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[519.194, 3.129, 183.207]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere234_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[504.258, 3.129, 183.28]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere235_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[511.589, 3.129, 180.493]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere236_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[420.079, -0.349, 163.868]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere237_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[410.242, -0.349, 176.794]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere238_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[408.422, -0.349, 179.599]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere239_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[405.551, -0.349, 181.608]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere240_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[403.915, -0.349, 184.429]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere241_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[401.227, -0.349, 186.5]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere242_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[399.048, -0.349, 188.94]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere243_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[396.233, -0.349, 190.587]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere244_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[436.206, -0.349, 135.082]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere245_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[436.275, -0.349, 131.462]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere246_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[437.106, -0.349, 126.863]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere247_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[464.496, -0.349, 77.799]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere248_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[463.097, -0.349, 74.288]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere249_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[460.403, -0.349, 72.238]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere250_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[457.186, -0.349, 70.802]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere251_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[433.581, -0.349, 232.371]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere252_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[447.276, -0.349, 233.236]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere253_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[461.818, -0.349, 231.999]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere254_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[468.754, -0.349, 231.999]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere255_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[475.69, -0.349, 231.999]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere256_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[482.626, -0.349, 231.999]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere257_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[432.19, -0.349, 213.788]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere258_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[436.593, -0.349, 207.42]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere259_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[440.161, -0.349, 200.832]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere260_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[433.393, -0.349, 196.156]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere261_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[452.766, -0.349, 200.828]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere262_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[520.341, -0.349, 223.335]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere263_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[547.543, -0.349, 218.021]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere264_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[543.094, -0.349, 198.122]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere265_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[509.365, -0.349, 219.755]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere266_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[508.124, -0.349, 212.573]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere267_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[590.707, -0.349, 199.737]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere268_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[594.543, -0.349, 196.267]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere269_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[598.379, -0.349, 192.796]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere270_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[593.143, -0.349, 167.401]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere271_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[596.782, -0.349, 171.145]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere272_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[600.421, -0.349, 174.889]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere273_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[540.55, -0.349, 164.011]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere274_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[512.056, 11.374, 148.837]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere275_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[564.899, -0.349, 152.442]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere276_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[572.713, -0.349, 145.464]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere277_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[575.402, -0.349, 140.848]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere278_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[579.306, -0.349, 137.604]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere279_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[516.943, 11.374, 148.017]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere280_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[529.559, 11.374, 146.096]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere281_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[535.615, 11.374, 144.941]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere282_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[488.219, 11.374, 96.092]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere283_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[488.227, 11.374, 89.638]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere284_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[506.058, 12.096, 81.398]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere285_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[509.067, 11.841, 73.675]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere286_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[503.224, 11.374, 117.46]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere287_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[513.773, 24.018, 109.971]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere288_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[517.697, 23.756, 118.474]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere289_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[517.105, 25.694, 108.064]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere290_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[521.028, 25.449, 116.568]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere291_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[520.144, 26.656, 105.446]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GeoSphere292_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[524.983, 26.745, 115.377]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Line003_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[510.312, -7.551, 155.936]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Line004_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[518.057, -2.569, 144.407]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Object034_Material_#2_0'].geometry}
        material={materials.Material_2}
        position={[510.312, -7.674, 155.936]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/island (1).glb')
